version: '3.3'

services:
   rabbitmq:
     image: rabbitmq:3-management
     hostname: rabbitmq
     environment:
       RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
       RABBITMQ_DEFAULT_USER: rabbitmq
       RABBITMQ_DEFAULT_PASS: rabbitmq
       RABBITMQ_DEFAULT_VHOST: "/"
     ports:
       - 15672:15672
       - 5672:5672

   db-camunda:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     ports:
       - 3306:3306
     environment:
       MYSQL_ROOT_PASSWORD: camunda
       MYSQL_DATABASE: camunda
       MYSQL_USER: camunda
       MYSQL_PASSWORD: camunda


volumes:
    db_data: {}